"use strict";
console.log("hey");
let myName68 = "aditya";
var age = 23;
var name2 = "uttra";
var myString = "hi how are you baby";
var ans1 = `my name is ${name2} and my age is ${age}`;
console.log(ans);
//converting the number value into string;
var myNumber = 89;
var myNumberToString = String(myNumber); //this is the first approach;
var myNumberToString2 = myNumber.toString();
console.log(typeof myNumberToString, myNumberToString2);
